version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:20.10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: SonarCloud Scan
          command: |
            npm install -g sonarqube-scanner
            sonar-scanner \
              -Dsonar.organization=$SONAR_ORG \
              -Dsonar.projectKey=$CIRCLE_PROJECT_REPONAME \
              -Dsonar.sources=./src \
              -Dsonar.tests=./src \
              -Dsonar.test.inclusions=**/*.test.js,**/*.spec.js \
              -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN
      - store_artifacts:
          path: build
          destination: build
      - store_test_results:
          path: coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build